apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-cloud-kubernetes-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spring-cloud-kubernetes-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]
  # - apiGroups: ["discovery.k8s.io"]
  #   resources: ["endpointslices", "configmaps", "pods", "services", "endpoints", "secrets"]
  #   verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-cloud-kubernetes-rolebinding
subjects:
- kind: ServiceAccount
  name: spring-cloud-kubernetes-sa
roleRef:
  kind: Role
  name: spring-cloud-kubernetes-role
  apiGroup: rbac.authorization.k8s.io